### ISSUE TITLE
Redesign profile settings page

### ISSUE THREAD

**Issue by aanderson55** [IIEADB/IIEADB.github.io#12]
Redesign and add edit personal information such as name, adress, username

**Comment by aanderson55** [comment]
https://mui.com/

**Comment by xDeZex** [comment]
https://github.com/IIEADB/IIEADB.github.io/pull/20

**Comment by aanderson55** [comment]
Bra! Lagt lite kommentarer
#20

**Comment by xDeZex** [comment]
https://github.com/IIEADB/IIEADB.github.io/pull/22

**Comment by MiniMarius** [comment]
ok
