### ISSUE TITLE
Fix routing event

### ISSUE THREAD

**Issue by MiniMarius** [IIEADB/IIEADB.github.io#18]
When editing event, deleting team, creating team, we are now being navigated to dashboard/events every time instead of refreshing the current page.

Do also fix the /events/id endpoint to give the specific fields along with the leaderboard data

**Comment by MiniMarius** [comment]
https://github.com/IIEADB/CombiTrainer/commit/ddbe2ca1bf30bdb603fcfe28402a33ae1626d34d Fixed second part of ticket

**Comment by MiniMarius** [comment]
https://github.com/IIEADB/IIEADB.github.io/commit/0ef2431b1c84520fd93ec44a152cf4a3f6ede68d

**Comment by MikeEr1** [comment]
OK
