### ISSUE TITLE
Admin dashboard for event

### ISSUE THREAD

**Issue by MiniMarius** [IIEADB/IIEADB.github.io#8]
Create a admin dashboard for managing events in the web. Design + make it happen

**Comment by MiniMarius** [comment]
Functionality:

- [x] See list of all events
- [x] Create event
- [x] Delete Event
- [x] Add participants
- [x] Remove participants
- [x] Create team
- [x] delete team
- [x] Event name and time period in event page
- [x] Edit event

**Comment by aanderson55** [comment]
https://mui.com/
